SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS "TOTAL"
    FROM JULY
    GROUP BY FLAVOR) AS J
    ON J.FLAVOR = F.FLAVOR
ORDER BY J.TOTAL + F.TOTAL_ORDER DESC
LIMIT 3;
