SELECT B.CATEGORY AS "CATEGORY", SUM(S.SALES) AS "TOTAL_SALES"
FROM BOOK_SALES S
JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 01
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
